/*
* 包含多个action类型常量
* */

const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'
const USER_UPDATE = 'USER_UPDATE'
const USER_STATUS_RESET = 'USER_UPDATE_ERR'
const ERROR_MSG = 'ERROR_MSG'
const SENT_REQ = 'SENT_REQUEST'
const RCVD_RES = 'RECEIVED_RESPONSE'
const USER_LIST = 'USERS_LIST'
const MESSAGE_DATA = 'MESSAGE_LIST'
const RECEIVE_SINGLE_MSG = 'RECEIVE_SINGLE_MSG'
const MESSAGE_HAS_READ = 'MESSAGE_HAS_READ'

export
{
  USER_AUTH_SUCCESS,
  ERROR_MSG,
  SENT_REQ,
  RCVD_RES,
  USER_UPDATE,
  USER_STATUS_RESET,
  USER_LIST,
  MESSAGE_DATA,
  RECEIVE_SINGLE_MSG,
  MESSAGE_HAS_READ
}
