/*
* 包含多个action类型常量
* */

// const USER_REG_SUCCESS = 'USER_REG_SUCCESS'
const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'
const USER_UPDATE = 'USER_UPDATE'
const USER_STATUS_RESET = 'USER_UPDATE_ERR'
const ERROR_MSG = 'ERROR_MSG'
const SENT_REQ = 'SENT_REQUEST'
const USER_LIST = 'USERS_LIST'

export {USER_AUTH_SUCCESS, ERROR_MSG, SENT_REQ, USER_UPDATE ,USER_STATUS_RESET, USER_LIST}
